# $Id: Makefile,v 1.4 2004/12/21 11:53:53 rn Exp $

PREFIX?=/usr/local

all:

install:
	install -c -m 444 bstrbcpl.txt $(PREFIX)/share/doc/bcplkit
	install -c -m 444 intcode.txt  $(PREFIX)/share/doc/bcplkit
	install -c -m 444 manual.txt   $(PREFIX)/share/doc/bcplkit

clean:
